name: ci.yml
on: [pull_request, push, workflow_dispatch]

jobs:
  Zap-Scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run ZAP Full Scan
        uses: zaproxy/action-baseline@master
        with:
          target: https://devsecopsvm.m2pfintech.com # Replace with your target URL
          output: report_html.html  # Specify the output file name for XML report

      - name: Install tidy
        run:  apt-get install tidy -y
      
      - name: Convert HTML to XML
        run: tidy -q -asxml --numeric-entities yes report_html.html >file.xml
          
      - name: list
        run: |
          ls 
          cat file.xml        
              
