name: ci.yml

on:
  push:
    branches:
      - main
jobs:
  Zap-Scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run ZAP Full Scan
        uses: zaproxy/action-baseline@master
        with:
          target: https://www.shabdkosh.com # Replace with your target URL
          output: report_html.html  # Specify the output file name for XML report

      - name: run Install tidy
        run: sudo apt-get install -y tidy

      - name: Convert HTML to XML using tidy
        run: tidy -q -xml -o output.xml report_html.html
          
      - name: list
        run: |
          ls 
          cat output.xml       
              
