name: ci.yml

on:
  push:
    branches:
      - zapscan
jobs:
  Zap-Scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create XML placeholder file
        run: |
          touch report_xml.xml
          chmod a+w report_xml.xml
          
      - name: Run ZAP Full Scan
        uses: zaproxy/action-baseline@master
        with:
          target: https://www.shabdkosh.com
          cmd_options: '-x'
          
      - name: list
        run: |
          ls 
          cat report_xml.xml         
          
      # - name: Convert JSON to XML
      #   run: |
      #     jq -r 'def json2xml: . as $in | reduce keys_unsorted[] as $key (""; . + "<\($key)>\($in[$key] | if type == \"object\" then json2xml else . end)</\($key)>") | json2xml' report_json.json > output.xml
      #   working-directory: ${{ github.workspace }}
                 
      # - name: list
      #   run: |
      #     ls 
      #     cat output.xml     
              
              
