name: ci.yml

on:
  push:
    branches:
      - master

jobs:
  Gitleaks-scan:
    runs-on: Ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Gitleaks
        run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v7.4.1/gitleaks-linux-amd64
          chmod +x gitleaks-linux-amd64
          sudo mv gitleaks-linux-amd64 /usr/local/bin/gitleaks

      - name: Run Gitleaks
        run: gitleaks detect --source . --log-opts="--all commitA..commitB  

