name: ci.yml

on:
  push:
    branches:
      - zapscan
jobs:
  Zap-Scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: sanjeeveejayabalan/action:zap
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.zaproxy.org/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
            
      # - name: Checkout repository
      #   uses: actions/checkout@v2
        
      # - name: Install tidy
      #   run: sudo apt-get install -y tidy
        
      # - name: Convert HTML to XML
      #   run: |
      #     tidy -asxml report_html.html > output.xml
      #   working-directory: ${{ github.workspace }}
        
      # - name: Commit XML file
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "Convert HTML to XML"
      #     file_pattern: "output.xml"     
              
              
