name: ci.yml

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install gitleaks
        run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v7.4.1/gitleaks-linux-amd64 -O gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Run gitleaks scan
        run: |
          gitleaks --verbose --path=. --report=gitleaks-report.txt
          
      - name: Display Gitleaks report
        run: cat gitleaks-report.txt

          
  sonarqube-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install -B

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dependency-track-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.0.0/dependency-check-7.0.0-release.zip
          unzip dependency-check-7.0.0-release.zip
          java -jar dependency-check/bin/dependency-check.sh --scan . --format "ALL" --project "Your_Project_Name" --out /tmp/dependency-check-report
          
      - name: Display Dependency-Track report
        run: cat /tmp/dependency-check-report/dependency-check-report.json

      - name: Upload Dependency-Track report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-track-report
          path: /tmp/dependency-check-report  

  jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Adjust the Java version as needed

    - name: Make script executable
      run: chmod +x dependency-check/bin/dependency-check.sh

    - name: Run Dependency Check
      run: ./dependency-check/bin/dependency-check.sh      
