name: Scheduled Workflow
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
    
jobs:
  sample_job:
    name: Sample Job
    runs-on: generic-ci
    steps:
      - name: Display Current Time
        run: echo "The current time is $(date)"
        

      # - name: Checkout repository
      #   uses: actions/checkout@v2
        
      # - name: Install tidy
      #   run: sudo apt-get install -y tidy
        
      # - name: Convert HTML to XML
      #   run: |
      #     tidy -asxml report_html.html > output.xml
      #   working-directory: ${{ github.workspace }}
        
      # - name: Commit XML file
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "Convert HTML to XML"
      #     file_pattern: "output.xml"     
              
              
